# Generated by Django 4.2.1 on 2023-05-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticker',
            new_name='Stock',
        ),
    ]
